### ISSUE TITLE
about frelu?

### ISSUE THREAD

**Issue by daixiangzi** [nekitmm/FunnelAct_Pytorch#1]
why only replace relu on Bottleneck,but not replace in ResNet

**Comment by nekitmm** [comment]
This is just exactly what they did in the original paper (Bottleneck is part of the ResNet model). They did not replace all the ReLUs with FReLUs, but only part of them. You can kinda play with that if you want.

**Comment by daixiangzi** [comment]
> This is just exactly what they did in the original paper (Bottleneck is part of the ResNet model). They did not replace all the ReLUs with FReLUs, but only part of them. You can kinda play with that if you want.

ok,i know, thank for your reply
